### ISSUE TITLE
Error while running create script

### ISSUE THREAD

**Issue by potherca** [WouterHendriks/wh-creator#2]
This may or may not be a problem, but the create-script ran with errors for me:
```
## - Creating webdesign in repository and a new site in the Publisher ##

Sending soft-reset request... done
At module::system/internal/resources.whlib(39,9)
Error: Exception EXCEPTION: Cannot decode resourcename ''.

At module::system/internal/resources.whlib(39,9) (GETDISKPATHFORRESOURCE)
At module::system/internal/devtools/support.whlib(115,27) (SETUPWEBDESIGN)
At direct::/Users/ben/dev/webhare/whtree/var/installedmodules/next-nerd-coming-to.nerds.company/scripts/setup_new_webdesign.whscr(31,17) (:INITFUNCTION)

## - Cleaning up ##
```

**Comment by WouterHendriks** [comment]
Yikes! What title did you use when creating the site?

**Comment by potherca** [comment]
`next-nerd-coming-to.nerds.company`

**Comment by potherca** [comment]
Using a simpler name works. 

A check should be added to make sure the user inputs a valid name.

What are the constraints the name should adhere to?

**Comment by WouterHendriks** [comment]
It should be a valid folder name (`getfoldername()` should fix that, assuming dots are valid in folder names, which they are) and a valid WebHare module name.

Dots aren't valid in WH module names though (because variables in HareScript also don't allow dots).

Pushed a new version that substitutes '.' with '_' (and '-' with '_' while I was at it, to prevent naming the folder 'next-nerd-coming-to_nerds_company', mixing '-' with '_')

**Comment by potherca** [comment]
The `str` variable is redundant. Also, wouldn't it be easier to just convert _all_ punctuation characters to dash '-'?

Then you'd only have:
```bash
function converttofoldername()
{
  local output="$@"

  output=$(echo $output | tr '[:upper:]' '[:lower:]')
  output=$(echo $output | tr '[:punct:]'  '-')

  echo $output
}
```

This _could_ be shortened even more:

```bash
function converttofoldername()
{
    echo "$@" | tr '[:upper:][:punct:]' '[:lower:]-'
}
```
